<?php
/**
 * install/products_seed.php — 10 initial marketplace products.
 * Returns array; config.php inserts each row and guards with products_seeded_v1.
 */
return [
    [
        'slug'           => 'canva-pro-subscription',
        'name'           => 'Canva Pro — اشتراك سنوي',
        'category'       => 'digital',
        'short'          => 'أداة التصميم الأولى عالمياً — قوالب احترافية لا نهاية لها، AI، وإزالة الخلفيات.',
        'desc'           => '<p>Canva Pro هو أشهر أداة تصميم في العالم تُستخدم لإنشاء المنشورات، اللوجوهات، العروض التقديمية، وأكثر من 400 نوع من التصاميم. النسخة Pro تُضيف مكتبة ضخمة من القوالب المدفوعة، أدوات AI لتوليد الصور وإزالة الخلفية، وتخزيناً سحابياً بلا حدود.</p><ul><li>أكثر من 100 مليون قالب وعنصر تصميمي</li><li>أدوات الذكاء الاصطناعي: Magic Resize، Background Remover، Magic Write</li><li>تخزين سحابي 1TB</li><li>جدولة منشورات السوشيال ميديا مباشرةً</li></ul>',
        'price'          => 119.99,
        'original_price' => 149.99,
        'currency'       => 'USD',
        'icon'           => '<path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-1 14H9V8h2v8zm4 0h-2V8h2v8z"/>',
        'color'          => '#7c3aed',
        'bg'             => '#f5f3ff',
        'buy_url'        => 'https://www.canva.com/pro/',
        'badge'          => 'الأكثر مبيعاً',
        'rating'         => 4.8,
        'reviews'        => 1240,
    ],
    [
        'slug'           => 'chatgpt-plus-subscription',
        'name'           => 'ChatGPT Plus — اشتراك شهري',
        'category'       => 'digital',
        'short'          => 'الوصول الكامل لـ GPT-4o مع DALL-E وتوليد الصور والتحليل المتقدم.',
        'desc'           => '<p>ChatGPT Plus يمنحك وصولاً غير محدود لأقوى نماذج OpenAI: GPT-4o للمحادثات، DALL-E 3 لتوليد الصور، وتحليل البيانات والمستندات. مثالي للمطورين، كتّاب المحتوى، والمحترفين.</p><ul><li>GPT-4o بدون قيود</li><li>DALL-E 3 لتوليد الصور</li><li>تحليل PDF والجداول</li><li>الوصول المبكر للمميزات الجديدة</li></ul>',
        'price'          => 20.00,
        'original_price' => null,
        'currency'       => 'USD',
        'icon'           => '<circle cx="12" cy="12" r="10"/><path d="M8 12h8M12 8v8" stroke="white" stroke-width="2"/>',
        'color'          => '#10a37f',
        'bg'             => '#f0fdf4',
        'buy_url'        => 'https://chat.openai.com/',
        'badge'          => 'جديد',
        'rating'         => 4.7,
        'reviews'        => 3820,
    ],
    [
        'slug'           => 'nordvpn-2-year-plan',
        'name'           => 'NordVPN — خطة سنتين',
        'category'       => 'digital',
        'short'          => 'أسرع VPN في العالم — حماية كاملة وفتح المحتوى المحجوب بنقرة واحدة.',
        'desc'           => '<p>NordVPN هو الـVPN المُفضّل لـ 14 مليون مستخدم حول العالم. يُشفّر اتصالك الإنترنت ويُخفي عنوان IP ويفتح المحتوى الجغرافي المقيّد من Netflix وYouTube وغيرها. خطة السنتين توفّر 70% مقارنةً بالاشتراك الشهري.</p><ul><li>5400+ سيرفر في 60 دولة</li><li>حماية 6 أجهزة في نفس الوقت</li><li>سرعات تدفق فيديو 4K بدون تأخير</li><li>ضمان استرداد الأموال 30 يوماً</li></ul>',
        'price'          => 79.99,
        'original_price' => 263.76,
        'currency'       => 'USD',
        'icon'           => '<path d="M12 1L3 5v6c0 5.55 3.84 10.74 9 12 5.16-1.26 9-6.45 9-12V5l-9-4z"/>',
        'color'          => '#4338ca',
        'bg'             => '#eef2ff',
        'buy_url'        => 'https://nordvpn.com/',
        'badge'          => 'وفّر 70%',
        'rating'         => 4.6,
        'reviews'        => 892,
    ],
    [
        'slug'           => 'adobe-creative-cloud-all-apps',
        'name'           => 'Adobe Creative Cloud — جميع التطبيقات',
        'category'       => 'digital',
        'short'          => 'Photoshop + Illustrator + Premiere + After Effects وأكثر من 20 تطبيقاً.',
        'desc'           => '<p>Adobe Creative Cloud يمنحك الوصول لأكثر من 20 تطبيقاً من Photoshop للتعديل على الصور، وIllustrator للرسوم المتجهة، وPremiere Pro لمونتاج الفيديو، وAfter Effects للموشن جرافيك. الحل الشامل للمحترفين الإبداعيين.</p><ul><li>Photoshop, Illustrator, Premiere Pro, After Effects</li><li>100GB تخزين سحابي</li><li>Adobe Fonts — آلاف الخطوط المرخّصة</li><li>تحديثات مستمرة وأدوات AI جديدة</li></ul>',
        'price'          => 54.99,
        'original_price' => 79.99,
        'currency'       => 'USD',
        'icon'           => '<path d="M19.5 3h-15A1.5 1.5 0 003 4.5v15A1.5 1.5 0 004.5 21h15a1.5 1.5 0 001.5-1.5v-15A1.5 1.5 0 0019.5 3zM9 15H7l3-9 2 6 2-4 3 7h-2l-1.5-4L12 15l-1.5-3.5L9 15z"/>',
        'color'          => '#dc2626',
        'bg'             => '#fef2f2',
        'buy_url'        => 'https://www.adobe.com/creativecloud/',
        'badge'          => 'عرض محدود',
        'rating'         => 4.5,
        'reviews'        => 2100,
    ],
    [
        'slug'           => 'apple-airpods-pro-2',
        'name'           => 'Apple AirPods Pro (الجيل الثاني)',
        'category'       => 'hardware',
        'short'          => 'أفضل سماعات لاسلكية في السوق — إلغاء ضوضاء استثنائي وصوت نقي.',
        'desc'           => '<p>AirPods Pro الجيل الثاني ترفع معايير السماعات اللاسلكية بإلغاء ضوضاء نشط متطور وصوت ثلاثي الأبعاد (Spatial Audio) يضعك في قلب الموسيقى. مقاومة للماء والعرق، وعمر بطارية يصل لـ30 ساعة مع الحافظة.</p><ul><li>إلغاء ضوضاء نشط H2</li><li>Spatial Audio وDolby Atmos</li><li>مقاومة ماء IP54</li><li>30 ساعة بطارية مع الحافظة</li></ul>',
        'price'          => 249.00,
        'original_price' => 279.00,
        'currency'       => 'USD',
        'icon'           => '<path d="M12 2a5 5 0 100 10A5 5 0 0012 2zm-7 9a7 7 0 1014 0"/>',
        'color'          => '#1d4ed8',
        'bg'             => '#eff6ff',
        'buy_url'        => 'https://www.apple.com/airpods-pro/',
        'badge'          => 'الأكثر مبيعاً',
        'rating'         => 4.9,
        'reviews'        => 4530,
    ],
    [
        'slug'           => 'logitech-mx-master-3s',
        'name'           => 'Logitech MX Master 3S — ماوس احترافي',
        'category'       => 'hardware',
        'short'          => 'الماوس المفضّل للمحترفين — دقة 8000 DPI وعجلة تمرير مغناطيسية ساحرة.',
        'desc'           => '<p>MX Master 3S هو الماوس الاحترافي الذي يُغيّر طريقة عملك. عجلة التمرير المغناطيسية تُتيح تمرير آلاف السطور في لحظة، والدقة 8000 DPI تُناسب العمل الدقيق على الشاشات عالية الدقة. يعمل مع 3 أجهزة في نفس الوقت.</p><ul><li>دقة 8000 DPI قابلة للضبط</li><li>عجلة MagSpeed المغناطيسية الهادئة</li><li>توصيل 3 أجهزة بزر واحد</li><li>70 يوماً على شحنة واحدة</li></ul>',
        'price'          => 99.99,
        'original_price' => 119.99,
        'currency'       => 'USD',
        'icon'           => '<path d="M12 2C8.13 2 5 5.13 5 9v7l2 4h10l2-4V9c0-3.87-3.13-7-7-7z"/>',
        'color'          => '#0369a1',
        'bg'             => '#f0f9ff',
        'buy_url'        => 'https://www.logitech.com/en-us/products/mice/mx-master-3s.html',
        'badge'          => null,
        'rating'         => 4.8,
        'reviews'        => 1870,
    ],
    [
        'slug'           => 'samsung-t7-portable-ssd',
        'name'           => 'Samsung T7 1TB — SSD محمول',
        'category'       => 'hardware',
        'short'          => 'ذاكرة تخزين خارجية خفيفة وسريعة — نقل 1 جيجابايت في أقل من 5 ثوانٍ.',
        'desc'           => '<p>Samsung T7 هو الـSSD المحمول المثالي للمصوّرين والمحررين الذين يحتاجون لنقل ملفات ضخمة بسرعة. وزنه 58 جراماً فقط ويسع 1 تيرابايت بسرعات قراءة حتى 1050 MB/s. متوافق مع جميع الأجهزة عبر USB-C.</p><ul><li>سرعة قراءة 1050 MB/s</li><li>وزن 58 جراماً فقط</li><li>مقاوم للصدمات AES 256-bit</li><li>USB-C مع USB-A adapter</li></ul>',
        'price'          => 89.99,
        'original_price' => 109.99,
        'currency'       => 'USD',
        'icon'           => '<rect x="3" y="7" width="18" height="10" rx="2"/><path d="M7 12h.01M11 12h.01"/>',
        'color'          => '#0891b2',
        'bg'             => '#ecfeff',
        'buy_url'        => 'https://www.samsung.com/us/computing/memory-storage/portable-solid-state-drives/',
        'badge'          => 'وفّر 18%',
        'rating'         => 4.7,
        'reviews'        => 2340,
    ],
    [
        'slug'           => 'grammarly-business-yearly',
        'name'           => 'Grammarly Business — خطة سنوية',
        'category'       => 'digital',
        'short'          => 'تصحيح الكتابة الإنجليزية بالذكاء الاصطناعي — مثالي للفرق والشركات.',
        'desc'           => '<p>Grammarly Business هو الحل الاحترافي لضمان كتابة إنجليزية خالية من الأخطاء لفريقك بأكمله. يتكامل مع Gmail وSlack وMicrosoft Office ويقدّم اقتراحات نغمة وأسلوب متقدمة تتجاوز مجرد تصحيح الإملاء.</p><ul><li>تصحيح نحوي وإملائي متقدم</li><li>اقتراحات الوضوح والأسلوب</li><li>لوحة تحكم الفريق والإحصائيات</li><li>يعمل مع 500,000+ موقع وتطبيق</li></ul>',
        'price'          => 15.00,
        'original_price' => 25.00,
        'currency'       => 'USD',
        'icon'           => '<path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"/>',
        'color'          => '#059669',
        'bg'             => '#ecfdf5',
        'buy_url'        => 'https://www.grammarly.com/business',
        'badge'          => 'شهرياً',
        'rating'         => 4.5,
        'reviews'        => 980,
    ],
    [
        'slug'           => 'keychron-k2-pro-keyboard',
        'name'           => 'Keychron K2 Pro — كيبورد ميكانيكي',
        'category'       => 'hardware',
        'short'          => 'الكيبورد الميكانيكي الأفضل للمحترفين — ضغطات دقيقة وإضاءة RGB مذهلة.',
        'desc'           => '<p>Keychron K2 Pro هو الكيبورد الميكانيكي المفضّل للمبرمجين والكتّاب. يأتي بمفاتيح Gateron Pro التي توفّر تجربة كتابة مريحة حتى بعد ساعات من العمل. يتصل لاسلكياً بـ3 أجهزة في وقت واحد.</p><ul><li>مفاتيح Gateron Pro Tactile</li><li>لاسلكي Bluetooth 5.1 لـ3 أجهزة</li><li>بطارية 4000mAh</li><li>إضاءة RGB قابلة للتخصيص</li></ul>',
        'price'          => 99.99,
        'original_price' => 119.99,
        'currency'       => 'USD',
        'icon'           => '<rect x="2" y="6" width="20" height="12" rx="2"/><path d="M6 10h.01M10 10h.01M14 10h.01M18 10h.01M8 14h8"/>',
        'color'          => '#92400e',
        'bg'             => '#fffbeb',
        'buy_url'        => 'https://www.keychron.com/products/keychron-k2-pro-qmk-via-wireless-mechanical-keyboard',
        'badge'          => null,
        'rating'         => 4.6,
        'reviews'        => 756,
    ],
    [
        'slug'           => 'notion-plus-yearly',
        'name'           => 'Notion Plus — اشتراك سنوي للفريق',
        'category'       => 'digital',
        'short'          => 'نظام إدارة المعرفة والمشاريع — يجمع الملاحظات، قواعد البيانات، والتعاون في مكان واحد.',
        'desc'           => '<p>Notion Plus هو أداة الإنتاجية الشاملة التي تحوّل طريقة عملك: قواعد بيانات، مهام، وثائق، وويكي داخلية كلها في مكان واحد. مع Notion AI يمكنك تلخيص أي صفحة وكتابة محتوى جديد في ثوانٍ.</p><ul><li>مساحة عمل لا محدودة</li><li>Notion AI مدمج</li><li>تعاون الفريق في الوقت الفعلي</li><li>تكامل مع Slack وJira وGitHub</li></ul>',
        'price'          => 8.00,
        'original_price' => 16.00,
        'currency'       => 'USD',
        'icon'           => '<path d="M4 4h16v16H4V4zm4 4h8M8 12h8M8 16h5"/>',
        'color'          => '#1e1e1e',
        'bg'             => '#f9fafb',
        'buy_url'        => 'https://www.notion.so/pricing',
        'badge'          => 'وفّر 50%',
        'rating'         => 4.7,
        'reviews'        => 1560,
    ],
];
